- hosts: all
  user: ubuntu
  become: true
  connection: ssh
  tasks:
   - name : update the instance
     command : sudo apt get update
   - name: Install docker
     command: sudo apt install -y docker.io
   - name: start docker
     command : sudo systemctl start docker
   - name: start container
     command: docker run -td -p 8080:8080 ariz1985/bankingandfinanceapp1.0
