- name : Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
   - name : update the instance
     command : sudo apt update
     
   - name: Install docker
     command: sudo apt install -y docker.io 
     
   - name: start docker
     command : sudo systemctl start docker
     
   - name: start container
     command: docker run -itd -p 8084:8081 ariz1985/bankingandfinanceapp1.0
